name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Authenticate with service account
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDKs
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Set environment variables
      run: |
        echo "ESESOFTWARE_SECRET_KEY_FOR_CONTACT_BOX=${{ secrets.ESESOFTWARE_SECRET_KEY_FOR_CONTACT_BOX }}" >> $GITHUB_ENV
        echo "ESESOFTWARE_SECRET_KEY_FOR_CONTACT_BOX=${{ secrets.ESESOFTWARE_SECRET_KEY_FOR_CONTACT_BOX }}" >> $GITHUB_WORKSPACE/.env
        echo "EMAIL_APPLICATION_KEY=${{ secrets.EMAIL_APPLICATION_KEY }}" >> $GITHUB_ENV
        echo "EMAIL_APPLICATION_KEY=${{ secrets.EMAIL_APPLICATION_KEY }}" >> $GITHUB_WORKSPACE/.env

    - name: Set GOOGLE_APPLICATION_CREDENTIALS environment variable
      run: |
        echo "${{ secrets.GCP_APP_KEY_64 }}" | base64 --decode > $HOME/gcp_key.json
        echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcp_key.json" >> $GITHUB_ENV
        gcloud app deploy --quiet